/**
 * The pose guide.
 *
 * A try-on is only as good as the photo it's given, and people hand us bad ones:
 * cropped at the knees, backlit, arms folded over the garment. So the camera
 * reads the scene, picks a pose that suits it, and draws that pose as a
 * silhouette on the live view for them to stand into.
 *
 * Every pose here keeps the torso and legs unobstructed — a pose the shopper
 * looks great in but that hides the clothes would defeat the entire point.
 */

export interface Pose {
  slug: string;
  name: string;
  /** Shown under the viewfinder. */
  cue: string;
  /** When this pose is the right call — fed to the model as selection criteria. */
  suits: string;
  /** How the silhouette is generated. */
  prompt: string;
  /** Silhouette overlay, generated by scripts/seed-poses.ts. */
  image: string;
}

const P = (
  slug: string,
  name: string,
  cue: string,
  suits: string,
  prompt: string,
): Pose => ({
  slug,
  name,
  cue,
  suits,
  prompt,
  image: `/poses/${slug}.png`,
});

export const POSES: Pose[] = [
  P(
    "straight",
    "Straight On",
    "Face the camera. Arms relaxed at your sides, feet shoulder-width apart.",
    "The default. Plain background, even light, room to fit the whole body in frame. Gives the cleanest try-on.",
    "standing straight facing the viewer, arms relaxed down at the sides slightly away from the body, feet shoulder-width apart, head level",
  ),
  P(
    "contrapposto",
    "Weight Shift",
    "Put your weight on one leg, let the other relax. Shoulders square to the camera.",
    "A relaxed, natural stance. Good when the shopper looks stiff, and when there's clear space around them.",
    "standing with weight on one leg in a relaxed contrapposto stance, hips slightly tilted, arms loose at the sides, facing the viewer",
  ),
  P(
    "hands-pockets",
    "Hands in Pockets",
    "Hook your thumbs or hands loosely in your pockets. Stand tall.",
    "Casual and easy. Good for denim and streetwear. Keeps the torso fully visible.",
    "standing facing the viewer with both hands tucked casually into trouser pockets, elbows slightly out, standing tall",
  ),
  P(
    "hand-hip",
    "Hand on Hip",
    "One hand on your hip, the other relaxed. Angle one foot forward.",
    "Confident and flattering. Works for dresses, kurtis and tailoring where you want to show the waist.",
    "standing facing the viewer with one hand resting on the hip and the other arm relaxed at the side, one foot angled forward",
  ),
  P(
    "three-quarter",
    "Three-Quarter Turn",
    "Turn your body about 45°, keep your face to the camera.",
    "Slims the silhouette and shows the cut of a garment from the side. Needs space to the left or right.",
    "standing turned about forty-five degrees away from the viewer with the head turned back to face the viewer, arms relaxed",
  ),
  P(
    "walking",
    "Mid-Stride",
    "Take a step towards the camera and freeze mid-step.",
    "Energetic, shows how a garment moves. Needs depth — a corridor, a path, open floor.",
    "captured mid-stride walking towards the viewer, one leg forward, arms swinging naturally",
  ),
  P(
    "lean",
    "Leaning",
    "Lean one shoulder against the wall, cross one ankle over the other.",
    "Only when there's a clean wall right beside them. Relaxed and editorial.",
    "standing leaning sideways against a wall with one shoulder, ankles crossed, arms relaxed",
  ),
  P(
    "arms-crossed",
    "Arms Crossed",
    "Fold your arms loosely across your chest. Feet planted.",
    "Strong and grounded. AVOID for tops and prints — the arms cover the chest.",
    "standing facing the viewer with arms folded loosely across the chest, feet planted shoulder-width apart",
  ),
];

export const poseBySlug = (slug: string) => POSES.find((p) => p.slug === slug);
