import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Users } from "lucide-react";
import { prisma } from "@/lib/db";
import { Aurora } from "@/components/aurora";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = {
  title: "The Feed",
  description:
    "Real people in real clothes — every look here was generated by someone who chose to share it.",
};

// Shared looks change as people post; don't serve a stale page for an hour.
export const revalidate = 60;

export default async function FeedPage() {
  // `inFeed`, not `shared` — a share link is not consent to be on a public
  // gallery. Nothing appears here that its owner didn't explicitly post.
  const looks = await prisma.look.findMany({
    where: { inFeed: true },
    orderBy: { createdAt: "desc" },
    take: 60,
    include: {
      garments: { include: { garment: true } },
      user: { select: { username: true } },
    },
  });

  return (
    <div className="relative min-h-dvh overflow-hidden px-6 pt-32 pb-24">
      <Aurora />

      <div className="mx-auto max-w-7xl">
        <header>
          <h1 className="font-display text-5xl text-bone-50 sm:text-6xl">
            The <span className="text-flare italic">Feed</span>
          </h1>
          <p className="mt-4 max-w-xl text-bone-400">
            Real people, not models. Every look here was made by someone who chose
            to share it.
          </p>
        </header>

        {looks.length === 0 ? (
          <Reveal className="mt-16">
            <div className="hairline flex flex-col items-center rounded-2xl border border-dashed py-24 text-center">
              <Users className="size-6 text-bone-500" />
              <p className="mt-5 font-medium text-bone-100">Nothing shared yet.</p>
              <p className="mt-2 max-w-xs text-sm text-bone-400">
                Be the first — fit a look, then hit share.
              </p>
              <Link
                href="/studio"
                className="mt-8 rounded-full bg-bone-100 px-6 py-3 text-sm font-medium text-ink-950 transition-transform hover:scale-[1.03] active:scale-95"
              >
                Open the Studio
              </Link>
            </div>
          </Reveal>
        ) : (
          <div className="mt-14 grid grid-cols-2 gap-6 lg:grid-cols-4">
            {looks.map((look, i) => {
              const label =
                look.kind === "haircut"
                  ? (look.title ?? "A new cut")
                  : look.garments.map((g) => g.garment.name).join(" · ");

              return (
                <Reveal key={look.id} delay={(i % 4) * 0.06}>
                  <Link href={`/share/${look.id}`} className="group block">
                    <div
                      className={`relative overflow-hidden rounded-xl bg-ink-900 ${
                        look.kind === "haircut" ? "aspect-square" : "aspect-3/4"
                      }`}
                    >
                      {/* eslint-disable-next-line @next/next/no-img-element -- /api/media */}
                      <img
                        src={`/api/media/${look.imageKey}`}
                        alt={label}
                        loading="lazy"
                        className="size-full object-cover transition-transform duration-700 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover:scale-105"
                      />
                      <span className="glass absolute top-3 left-3 rounded-full px-2.5 py-1 text-[10px] tracking-wide text-bone-200 uppercase">
                        {look.kind === "haircut" ? "Haircut" : "Outfit"}
                      </span>
                    </div>

                    {look.user.username && (
                      <p className="mt-3 text-sm font-medium text-bone-50">
                        @{look.user.username}
                      </p>
                    )}
                    <p className="mt-0.5 line-clamp-2 text-sm leading-relaxed text-bone-400">
                      {label}
                    </p>
                  </Link>
                </Reveal>
              );
            })}
          </div>
        )}

        <Reveal delay={0.2}>
          <div className="mt-20 text-center">
            <Link
              href="/studio"
              className="group inline-flex items-center gap-2 rounded-full bg-bone-100 px-7 py-4 font-medium text-ink-950 transition-transform duration-300 hover:scale-[1.03] active:scale-95"
            >
              Make your own
              <ArrowRight className="size-4 transition-transform duration-300 group-hover:translate-x-1" />
            </Link>
          </div>
        </Reveal>
      </div>
    </div>
  );
}
